
  $(document).ready(function(){
    $("#myBtn").click(function(){
    $("#myModal").modal();
      });
  });
  $(document).ready(function(){
    $("#myBtn2").click(function(){
    $("#myModal2").modal();
      });
  });
  $(document).ready(function(){
    $("#myBtn3").click(function(){
    $("#myModal3").modal();
      });
  });
  $(document).ready(function(){
    $("#myBtn4").click(function(){
    $("#myModal4").modal();
      });
  });
  $(document).ready(function(){
    $("#myBtn5").click(function(){
    $("#myModal5").modal();
      });
  });
  $(document).ready(function(){
    $("#myBtn2").click(function(){
    $("#myModal2").modal();
      });
  });
